// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PG_DataAccess.Data;

namespace PG_DataAccess.Migrations
{
    [DbContext(typeof(PgDbContext))]
    partial class PgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PG_DataAccess.Models.PaymentRequest", b =>
                {
                    b.Property<Guid>("paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("cardHolder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("cardNumberMasked")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("expiryDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("paymentSuccessful")
                        .HasColumnType("bit");

                    b.HasKey("paymentId");

                    b.ToTable("paymentRequests");

                    b.HasData(
                        new
                        {
                            paymentId = new Guid("c0bea600-d903-4fad-ba5a-894447f0fdfe"),
                            amount = 100.00m,
                            cardHolder = "MR JOHN HAMILTON-SMITH",
                            cardNumberMasked = "************1234",
                            currency = "GBP",
                            dateCreated = new DateTime(2021, 3, 12, 22, 7, 17, 255, DateTimeKind.Utc).AddTicks(5316),
                            expiryDate = "06/21",
                            paymentSuccessful = true
                        },
                        new
                        {
                            paymentId = new Guid("45dc7403-1bc4-4b49-982f-466bbca8ba73"),
                            amount = 250.00m,
                            cardHolder = "MS JANE HAMILTON-SMITH",
                            cardNumberMasked = "************5678",
                            currency = "GBP",
                            dateCreated = new DateTime(2021, 3, 12, 22, 7, 17, 257, DateTimeKind.Utc).AddTicks(272),
                            expiryDate = "06/21",
                            paymentSuccessful = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
