version: '3.4'

services:
  # Database
  db:
    container_name: pg_sql_server
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    restart: on-failure
    #hostname: pg_sql_server
    ports:
      - 1433:1433
    expose:
      - 1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=5g89&Zm8YW573a
    volumes:
      - sqlvolume:/var/opt/mssql
      #- sqllog:/var/opt/sqlserver/log
      #- sqlbackup:/var/opt/sqlserver/backup

  # Payment Gateway
  pg-core:
    container_name: pg_core
    image: ${DOCKER_REGISTRY-}pgcore
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    build:
      context: .
      dockerfile: PG-Core/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=kD4AnSjH4etS48
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    links:
      - seq
    depends_on:
      - db

  # Seq
  seq:
    container_name: pg_seq
    image: datalust/seq:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 8G
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
      #- SEQ_FIRSTRUN_ADMINPASSWORDHASH=password
    volumes:
      - seq-storage:/data

  # Prometheus
  prometheus:
    container_name: pg_prometheus
    image: quay.io/prometheus/prometheus:latest
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  # Grafana
  grafana: 
    container_name: pg_grafana
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  sqlvolume:
  #sqllog:
  #sqlbackup:
  seq-storage:
  grafana-storage: