global:
  scrape_interval: 5s 

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'PG-Core-read-prometheus'
    # metrics_path defaults to '/metrics'
    static_configs:
      - targets: ['PG-Core:8080']