global:
  scrape_interval: 15s 

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'PG_Core_Read_Prometheus'
    static_configs:
      - targets: ['PG-Core:80']